In [2]:
import numpy as np

**1. Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:**
**anteriormente, extraed:**

In [4]:
array= np.random.rand (5,3)
array

array([[0.5771731 , 0.38704098, 0.72825127],
       [0.88815673, 0.0975105 , 0.31060616],
       [0.4308234 , 0.31576254, 0.35814817],
       [0.44932902, 0.00881954, 0.67663716],
       [0.32478538, 0.00944259, 0.12505365]])


- **El valor de la primera fila y la segunda columna.**

In [5]:
array[0,1] 

0.3870409822338019

- **Los valores de la segunda fila y las dos primeras columnas.**

In [7]:
array[1,:2] 

array([0.88815673, 0.0975105 ])

- **Extraed las filas pares (incluyendo la 0) y todas las columnas.**

In [10]:
array [::2,:]

array([[0.5771731 , 0.38704098, 0.72825127],
       [0.4308234 , 0.31576254, 0.35814817],
       [0.32478538, 0.00944259, 0.12505365]])

- **Extraed los valores que sean mayores que 0.5.**

In [12]:
#array > 0.5   #Esto devuelve true/false
 array [array > 0.5]

array([0.5771731 , 0.72825127, 0.88815673, 0.67663716])

- **Extraed los valores menores que 0.2 o mayores que 0.5**

In [13]:
array [(array<0.2) | (array > 0.5)]

array([0.5771731 , 0.72825127, 0.88815673, 0.0975105 , 0.00881954,
       0.67663716, 0.00944259, 0.12505365])

**2. Cread dos array de tres dimensiones:**

- **El primero de 2 matrices, 5 filas y 3 columnas.**

- **El segundo de 3 matrices, 2 filas y 5 columnas.**

In [16]:
array2 = np.random.randint(0,50, (2,5,3))
array3 = np.random.randint(0,50, (3,2,5))

array([[[ 6, 18, 48, 33, 32],
        [47, 21, 30, 19,  7]],

       [[21, 40,  2,  9, 15],
        [11, 17, 37,  7,  0]],

       [[24,  2,  5, 47, 42],
        [ 3,  5,  6,  5, 44]]])

- **Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.**

In [17]:
def propiedades (array):

    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.dtype)

propiedades(array2)

(2, 5, 3)
30
3
int64


- **Sumad los dos arrays. ¿Podéis? ¿Por qué?**

In [ ]:
array2 + array3

El resultado es: ValueError                                Traceback (most recent call last)
/tmp/ipykernel_344/144200592.py in <module>
----> 1 array2 + array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5)

No se puede sumar porque no tienen las mismas dimensiones.


- **Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:**

>>.reshape()

>>.transpose()


In [24]:
print(array3)
print(array2)
array4 = array2.reshape((3,2,5))
arraynueva = np.transpose(array2, (2,0,1))
array4

[[[ 6 18 48 33 32]
  [47 21 30 19  7]]

 [[21 40  2  9 15]
  [11 17 37  7  0]]

 [[24  2  5 47 42]
  [ 3  5  6  5 44]]]
[[[36 10 42]
  [38 37 17]
  [46 27 40]
  [43 15  5]
  [46  1 28]]

 [[ 1 13 22]
  [20  7 47]
  [27 26 24]
  [ 0 26 10]
  [ 5 20 46]]]


array([[[36, 10, 42, 38, 37],
        [17, 46, 27, 40, 43]],

       [[15,  5, 46,  1, 28],
        [ 1, 13, 22, 20,  7]],

       [[47, 27, 26, 24,  0],
        [26, 10,  5, 20, 46]]])

- **Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.**

In [26]:
array3 + array4
np.add(array3,arraynueva)

array([[[42, 56, 94, 76, 78],
        [48, 41, 57, 19, 12]],

       [[31, 77, 29, 24, 16],
        [24, 24, 63, 33, 20]],

       [[66, 19, 45, 52, 70],
        [25, 52, 30, 15, 90]]])