**Empezamos nuevo bloque de ejercicios de pair programming de NumPy.**

**En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.**

In [1]:
import numpy as np

**1. Cread tres arrays: de una, dos y tres dimensiones.**

**Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.**

**📌 Nota**

- **El array de 2 dimensiones debe ser de 2 filas y 3 columnas.**
- **El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas.**

In [2]:

lista = [1,2,3]
array = np.array(lista)
print("Array 1 dimension:", array)


array1 = np.random.rand(2,2,3)
print("Array 2 dimensiones:",array1)


array2 = np.random.rand(2,3,5)
print("Array multidimensional:", array2)

Array 1 dimension: [1 2 3]
Array 2 dimensiones: [[[0.03413219 0.93940571 0.14220484]
  [0.57495401 0.45551729 0.00622169]]

 [[0.77338464 0.31124018 0.49629057]
  [0.4408163  0.25194092 0.42330969]]]
Array multidimensional: [[[0.59021385 0.36435104 0.50820189 0.18744022 0.98885084]
  [0.83043241 0.75523747 0.42050663 0.84182247 0.85965776]
  [0.38083339 0.59645509 0.88255712 0.00481151 0.91639513]]

 [[0.29470774 0.59779862 0.09273716 0.03325381 0.97047456]
  [0.63125937 0.54634978 0.19411593 0.30247091 0.54902384]
  [0.62878913 0.78613947 0.4914036  0.03988693 0.43638404]]]


**2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.**

In [3]:
def propiedades (array):

    print(array.shape)
    print(array.size)
    print(array.ndim)
    print(array.dtype)

propiedades(array1)


(2, 2, 3)
12
3
float64


**3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas**

In [4]:
array3 = np.eye (3,3) #si permite mover la diagonal
print(array3)

array4 = np.identity (3) #no permite mover la diagonal
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.**

In [5]:
#array2 = np.random.rand(2,3,5)
#print(array2)

array5 = np.empty_like(array2)
print(array5)

[[[0.59021385 0.36435104 0.50820189 0.18744022 0.98885084]
  [0.83043241 0.75523747 0.42050663 0.84182247 0.85965776]
  [0.38083339 0.59645509 0.88255712 0.00481151 0.91639513]]

 [[0.29470774 0.59779862 0.09273716 0.03325381 0.97047456]
  [0.63125937 0.54634978 0.19411593 0.30247091 0.54902384]
  [0.62878913 0.78613947 0.4914036  0.03988693 0.43638404]]]


**5. Es el momento de hacer algunas operaciones entre arrays**

- **¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?**


In [ ]:
array1 = np.random.rand(2,2,3)
array4 = np.identity (3)

array6 = np.add(array1,array4)
print(array6)

# No se puede sumar por que no tienen la misma forma.

- **En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.**

In [7]:
array1 = np.random.rand(2,2,3)
print(array1)

array4 = np.ones_like(array1)
print(array4)

[[[0.58284763 0.18271297 0.70057675]
  [0.81339637 0.7608641  0.01666771]]

 [[0.07281987 0.08133908 0.20846806]
  [0.79741301 0.56423951 0.3931203 ]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Suma: [[[1.58284763 1.18271297 1.70057675]
  [1.81339637 1.7608641  1.01666771]]

 [[1.07281987 1.08133908 1.20846806]
  [1.79741301 1.56423951 1.3931203 ]]]


In [8]:
suma = array1 + array4
suma = np.add(array1,array4) 
print("Suma:",suma)

Suma: [[[1.58284763 1.18271297 1.70057675]
  [1.81339637 1.7608641  1.01666771]]

 [[1.07281987 1.08133908 1.20846806]
  [1.79741301 1.56423951 1.3931203 ]]]


- **Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.**

In [9]:
multi = array1 * array4
multiplicar = np.multiply(array1,array4) 
print("Multiplicar:", multi)

Multiplicar: [[[0.58284763 0.18271297 0.70057675]
  [0.81339637 0.7608641  0.01666771]]

 [[0.07281987 0.08133908 0.20846806]
  [0.79741301 0.56423951 0.3931203 ]]]


- **Dividid las dos matrices**

In [10]:
div = array1 / array4
dividir = np.divide(array1,array4) 
print("Dividir:", div)

Dividir: [[[0.58284763 0.18271297 0.70057675]
  [0.81339637 0.7608641  0.01666771]]

 [[0.07281987 0.08133908 0.20846806]
  [0.79741301 0.56423951 0.3931203 ]]]
