In [1]:
import numpy as np

**En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.**

**1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:**

In [2]:
array =  np.random.rand(2,3,5)
array = np.round(array, decimals =1)
array

array([[[0.6, 0.8, 0. , 0.6, 0.6],
        [0.3, 0.5, 0.5, 0.3, 0.4],
        [0.1, 0.7, 0.3, 0.9, 0.7]],

       [[0.3, 0.8, 0.4, 0.5, 0.2],
        [0.4, 0.9, 0. , 0.9, 0.1],
        [0.6, 1. , 0.9, 0.8, 0.1]]])

**2. Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.**

In [3]:
media_array = np.mean(array)
media_array = np.round(media_array, decimals =1)
media_array

0.5

**3. Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.**

In [4]:
max_array = np.max(array)
max_array = np.round(max_array, decimals =1)
max_array

1.0

**4. Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.**

In [5]:
min_array = np.min(array)
min_array = np.round(min_array, decimals =1)
min_array

0.0

**5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.**

In [6]:
array2 = np.empty((2,3,5))
array2


array([[[0.6, 0.8, 0. , 0.6, 0.6],
        [0.3, 0.5, 0.5, 0.3, 0.4],
        [0.1, 0.7, 0.3, 0.9, 0.7]],

       [[0.3, 0.8, 0.4, 0.5, 0.2],
        [0.4, 0.9, 0. , 0.9, 0.1],
        [0.6, 1. , 0.9, 0.8, 0.1]]])


**Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:**

>>- Si el valor del array es igual que la media, se reemplaza por "A".
>>- Si el valor del array es mayor que la media, se reemplaza por "B".
>>- Si el valor del array es menor que la media, se reemplaza por "C".
>>- Si el valor es igual que el máximo, se reemplaza por "D".
>>- Si el valor es igual que el mínimo, se reemplaza por "E".

In [7]:
array2 = np.empty((2,3,5), dtype= str)

for matriz in range(array.shape[0]):
    for fila in range(array.shape[1]):
        for columnas in range(array.shape[2]):
            n = array[matriz][fila][columnas]
            
            if n == media_array:
                letra = "A"
            elif n == max_array:
                letra = "D"
            elif n == min_array:
                letra = "E"
            elif n > media_array:
                letra = "B"
            elif n < media_array:
                letra = "C"
            
            array2[matriz][fila][columnas] = letra

array2

array([[['B', 'B', 'E', 'B', 'B'],
        ['C', 'A', 'A', 'C', 'C'],
        ['C', 'B', 'C', 'B', 'B']],

       [['C', 'B', 'C', 'A', 'C'],
        ['C', 'B', 'E', 'B', 'C'],
        ['B', 'D', 'B', 'B', 'C']]], dtype='<U1')

**💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.**

-------------------

**Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos.**

**Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.**
**En este caso:**

>>- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
>>- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
>>- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

**Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.**

In [21]:
array3= np.empty(shape=30,dtype = int)
index = 0

for matriz in range(array2.shape[0]):
    for fila in range(array2.shape[1]):
        for columnas in range(array2.shape[2]):
            letra = array2[matriz][fila][columnas]

            if  letra == 'A' or letra == 'B':
                n = 1
            elif letra == 'C' or letra == 'D':
                n = 2
            else:
                n = 3
                
            array3[index] = n
            index += 1

array3= np.reshape(array3,(2,3,5))

array3

array([[[1, 1, 3, 1, 1],
        [2, 1, 1, 2, 2],
        [2, 1, 2, 1, 1]],

       [[2, 1, 2, 1, 2],
        [2, 1, 3, 1, 2],
        [1, 2, 1, 1, 2]]])